name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup npm
        uses: actions/setup-node@v1

      - name: install antora
        run: npm i -g @antora/cli@2.1 @antora/site-generator-default@2.1

      - name: checkout code
        uses: actions/checkout@v1

      - name: build
        run: antora --fetch antora-playbook.yml

      - name: add cname/nojekyll
        run: |
          cp ./CNAME ./build/site
          touch ./build/site/.nojekyll

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
          publish_branch: gh-pages
          user_name: byuoitav
          user_email: oitav@byu.edu
